# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/xivo-call-logd/conf.d/

# Change the log level to debug level.
debug: false

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk

# Event bus (AMQP) connection informations
bus:
  username: guest
  password: guest
  host: localhost
  port: 5672
  exchange_name: xivo
  exchange_type: topic
  exchange_durable: True

# REST API server
rest_api:

  # Listening address
  listen: 0.0.0.0

  # Listening port
  port: 9298
  certificate: /usr/share/xivo-certs/server.crt
  private_key: /usr/share/xivo-certs/server.key

  #CORS configuration. See Flask-CORS documentation for other values.
  cors:

    #Enabled by default
    enabled: True

    #Allow JSON preflight requests
    allow_headers: [Content-Type, X-Auth-Token]

# xivo-auth (authentication daemon) connection informations.
auth:
  host: localhost
  port: 9497
  verify_certificate: /usr/share/xivo-certs/server.crt
  key_file: /var/lib/xivo-auth-keys/xivo-call-logd-key.yml

# xivo-confd (configuration daemon) connection informations.
confd:
  host: localhost
  port: 9486
  verify_certificate: /usr/share/xivo-certs/server.crt
