auth:
  host: auth
  verify_certificate: /usr/local/share/ssl/auth/server.crt
  key_file: /etc/xivo-call-logd/key.yml
db_uri: postgresql://asterisk:proformatique@postgres/asterisk
bus:
  host: rabbitmq
confd:
  host: confd
  verify_certificate: /usr/local/share/ssl/confd/server.crt
